--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigsmileXD/UserManager
build-by-default: true
branches:
- patch-2
projects:
  UserManager:
    path: ""
    libs:
    - src: thebigsmilexd/customui/customui
      version: ^3.0.0
    - src: poggit/libasynql/libasynql
      version: ^3.2.0
    - src: CortexPE/Commando/Commando
      version: ^0.5
...
